---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: exec
  labels:
    run: exec
spec:
  replicas: 1
  selector:
    matchLabels:
      run: exec
  template:
    metadata:
      labels:
        run: exec
    spec:
      containers:
      - name: exec
        image: in-cluster2
        ports:
        - containerPort: 4000
          protocol: TCP
        imagePullPolicy: Never
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 600
