# Service account with cluster roles. Its token will be mounted into exec pod.
---
apiVersion: v1
kind: List
items:
  - kind: ServiceAccount
    apiVersion: v1
    metadata:
      labels:
        app: che
      name: che
  - kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1beta1
    metadata:
      name: che-clusterrole-binding
    roleRef:
      kind: ClusterRole
      name: cluster-admin
      apiGroup: rbac.authorization.k8s.io
    subjects:
    - kind: ServiceAccount
      name: che
      namespace: default


